import { useState, useEffect, useRef } from 'react';
import { useLocation } from 'react-router-dom';

export default function TutorEngine() {
    const location = useLocation();
    const queryParams = new URLSearchParams(location.search);
    const initialTopic = queryParams.get('topic') || '';

    const [topic, setTopic] = useState(initialTopic);
    const [difficulty, setDifficulty] = useState('medium');
    const [loading, setLoading] = useState(false);
    const [result, setResult] = useState(null);

    const [isFlipped, setIsFlipped] = useState(false);
    const [selectedAnswers, setSelectedAnswers] = useState({});
    const [quizSubmitted, setQuizSubmitted] = useState(false);
    const [score, setScore] = useState(0);

    const hasAutoGenerated = useRef(false);

    useEffect(() => {
        if (initialTopic && !hasAutoGenerated.current) {
            hasAutoGenerated.current = true;
            handleGenerate();
        }
    }, [initialTopic]);

    const handleGenerate = async (e) => {
        if (e) e.preventDefault();
        setLoading(true);
        try {
            const baseUrl = import.meta.env.VITE_API_BASE_URL || (import.meta.env.PROD ? '' : 'http://localhost:5000');
            const res = await fetch(`${baseUrl}/api/learning/generate`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${localStorage.getItem('token')}`
                },
                body: JSON.stringify({ topic, difficulty })
            });
            
            if (res.status === 401) {
                localStorage.removeItem('token');
                window.location.reload();
                throw new Error('Unauthorized');
            }
            if (!res.ok) {
                throw new Error('Failed to generate practice material');
            }
            
            const data = await res.json();
            setResult(data);
            setIsFlipped(false);
            setSelectedAnswers({});
            setQuizSubmitted(false);
            setScore(0);
        } catch (err) {
            console.error(err);
        } finally {
            setLoading(false);
        }
    };

    const handleOptionSelect = (qIdx, opt) => {
        if (quizSubmitted) return;
        setSelectedAnswers(prev => ({ ...prev, [qIdx]: opt }));
    };

    const submitQuiz = async () => {
        if (!result || !result.quizzes) return;
        let calculatedScore = 0;
        const subtopicResults = [];
        
        result.quizzes.forEach((q, idx) => {
            const isCorrect = selectedAnswers[idx] === q.answer;
            if (isCorrect) {
                calculatedScore += 1;
            }
            subtopicResults.push({
                subtopic: q.subtopic || 'General Concepts',
                correct: isCorrect ? 1 : 0
            });
        });
        
        setScore(calculatedScore);
        setQuizSubmitted(true);

        try {
            const baseUrl = import.meta.env.VITE_API_BASE_URL || (import.meta.env.PROD ? '' : 'http://localhost:5000');
            await fetch(`${baseUrl}/api/learning/submit-quiz`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${localStorage.getItem('token')}`
                },
                body: JSON.stringify({
                    topic_id: result.topic_id,
                    score: calculatedScore,
                    total: result.quizzes.length,
                    subtopic_results: subtopicResults
                })
            });
        } catch (err) {
            console.error('Failed to save progress', err);
        }
    };

    return (
        <div className="animate-fade-in">
            <h1>AI Tutor Engine</h1>
            <p style={{ marginBottom: '2rem' }}>Generate custom practice material on any subject.</p>

            {!result ? (
                <div className="glass-panel">
                    <form style={{ display: 'grid', gap: '1.5rem' }} onSubmit={handleGenerate}>
                        <div>
                            <label style={{ display: 'block', marginBottom: '0.5rem', color: 'var(--text-muted)' }}>What do you want to learn?</label>
                            <input type="text" placeholder="e.g. Quantum Computing, React Hooks..." value={topic} onChange={e => setTopic(e.target.value)} required />
                        </div>
                        <div>
                            <label style={{ display: 'block', marginBottom: '0.5rem', color: 'var(--text-muted)' }}>Difficulty Level</label>
                            <select value={difficulty} onChange={e => setDifficulty(e.target.value)}>
                                <option value="easy">Beginner</option>
                                <option value="medium">Intermediate</option>
                                <option value="hard">Advanced</option>
                            </select>
                        </div>

                        <button type="submit" className="btn btn-accent" disabled={loading} style={{ alignSelf: 'start', marginTop: '1rem' }}>
                            {loading ? 'Synthesizing Knowledge...' : 'Generate Learning Module'}
                        </button>
                    </form>
                </div>
            ) : (
                <div className="animate-fade-in">
                    <button className="btn btn-secondary" onClick={() => setResult(null)} style={{ marginBottom: '2rem' }}>&larr; Learn Another Topic</button>

                    <div className="glass-panel" style={{ marginBottom: '2rem' }}>
                        <h3>Concept Explanation</h3>
                        <p style={{ color: 'white', marginTop: '1rem' }}>{result.explanation}</p>
                    </div>

                    <h3>Quick Flashcard</h3>
                    <div className="flashcard-container">
                        <div className={`flashcard ${isFlipped ? 'flipped' : ''}`} onClick={() => setIsFlipped(!isFlipped)}>
                            <div className="flashcard-front">
                                <div>
                                    <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginBottom: '1rem', textTransform: 'uppercase' }}>Tap to flip</div>
                                    {result.flashcard?.front || "What is this topic about?"}
                                </div>
                            </div>
                            <div className="flashcard-back">
                                {result.flashcard?.back || "This is the core concept."}
                            </div>
                        </div>
                    </div>

                    <h3 style={{ marginTop: '3rem' }}>Knowledge Check</h3>
                    {result.quizzes?.map((q, idx) => (
                        <div key={idx} className="glass-panel" style={{ marginTop: '1.5rem' }}>
                            <h4 style={{ color: 'var(--text-main)', marginBottom: '1rem' }}>{q.question}</h4>
                            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                                {q.options.map((opt, oIdx) => {
                                    const isSelected = selectedAnswers[idx] === opt;
                                    const isCorrect = quizSubmitted && opt === q.answer;
                                    const isWrong = quizSubmitted && isSelected && opt !== q.answer;
                                    
                                    let btnStyle = {};
                                    if (quizSubmitted) {
                                        if (isCorrect) btnStyle = {backgroundColor: 'rgba(16, 185, 129, 0.4)', borderColor: 'rgb(16, 185, 129)', color: 'white'};
                                        else if (isWrong) btnStyle = {backgroundColor: 'rgba(239, 68, 68, 0.4)', borderColor: 'rgb(239, 68, 68)', color: 'white'};
                                        else btnStyle = {opacity: 0.5};
                                    }

                                    return (
                                        <button 
                                            key={oIdx} 
                                            className={`btn ${isSelected && !quizSubmitted ? 'btn-primary' : 'btn-secondary'}`} 
                                            style={btnStyle}
                                            onClick={() => handleOptionSelect(idx, opt)}
                                            disabled={quizSubmitted}
                                        >
                                            {opt}
                                        </button>
                                    );
                                })}
                            </div>
                        </div>
                    ))}
                    
                    {!quizSubmitted && result.quizzes?.length > 0 && (
                        <button 
                            className="btn btn-accent" 
                            style={{marginTop: '2rem', width: '100%'}} 
                            onClick={submitQuiz}
                            disabled={Object.keys(selectedAnswers).length < result.quizzes.length}
                        >
                            {Object.keys(selectedAnswers).length < result.quizzes.length ? 'Answer all questions to submit' : 'Submit Quiz'}
                        </button>
                    )}
                    
                    {quizSubmitted && (
                        <div className="glass-panel animate-fade-in" style={{marginTop: '2rem', textAlign: 'center', background: 'linear-gradient(135deg, rgba(99,102,241,0.2), rgba(16,185,129,0.1))'}}>
                            <h3>Quiz Complete!</h3>
                            <h1 style={{fontSize: '3rem', color: 'var(--accent)', margin: '1rem 0'}}>{score} / {result.quizzes.length}</h1>
                            <h2 style={{color: 'white', marginBottom: '1rem'}}>{Math.round((score / result.quizzes.length) * 100)}% Accuracy</h2>
                            <p style={{color: 'var(--text-main)'}}>{score < result.quizzes.length ? "You seem to be lagging slightly in this topic based on the results. We've recorded this as a weak area in your dashboard." : "Perfect score! You have clearly mastered this concept."}</p>
                            
                            {(score / result.quizzes.length) < 0.9 && (
                                <div style={{ marginTop: '2rem', display: 'flex', flexDirection: 'column', gap: '1rem', alignItems: 'center' }}>
                                    <p style={{ color: 'var(--text-muted)' }}>Your score is below 90%. To improve your mastery, we suggest reviewing the material or trying again.</p>
                                    <div style={{ display: 'flex', gap: '1rem' }}>
                                        <button className="btn btn-secondary" onClick={() => window.open(`/learn?topic=${encodeURIComponent(topic)}`, '_blank')}>
                                            📺 Watch Learning Videos
                                        </button>
                                        <button className="btn btn-primary" onClick={handleGenerate}>
                                            🔄 Retest Now
                                        </button>
                                    </div>
                                </div>
                            )}
                        </div>
                    )}
                </div>
            )}
        </div>
    );
}
